using System.Text.Json.Serialization;

namespace TroubleTrack.Models
{
    internal class DataCollectionModel
    {
        public string Data { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [JsonIgnore]
        public bool Completed { get; set; } = false;

        [JsonIgnore]
        public bool Expanded { get; set; } = false;
    }

    internal class AnalysisModel
    {
        public string Summary { get; set; }
        public List<DataCollectionModel> DataCollection { get; set; }
    }

    public enum TroubleshootingDataType
    {
        // General environment information
        EnvironmentInfo,         // OS, .NET version, Installed SDKs, Hosting environment, etc.

        // Logs and diagnostics
        ApplicationLogs,         // Application-specific logs (e.g., Serilog, NLog, log4net, etc.)
        IISLogs,                 // IIS logs that capture requests and errors
        EventViewerLogs,         // Windows Event Viewer logs for application or system events
        ASPNetCoreLogs,          // Logs generated by ASP.NET Core middleware and host
        ExceptionDetails,        // Stack trace and exception messages

        // Configuration settings
        WebConfig,               // web.config file for ASP.NET Framework or IIS settings
        AppSettings,             // appsettings.json for ASP.NET Core configuration
        EnvironmentVariables,    // Key environment variables (e.g., ASPNETCORE_ENVIRONMENT)
        ConnectionStrings,       // Database connection string or other external service connections

        // Performance and load data
        PerformanceCounters,     // Windows performance counters (CPU, memory, request queues, etc.)
        CPUUsage,                // CPU usage data
        MemoryUsage,             // Memory usage details
        GCInfo,                  // Garbage collection information
        ThreadUsage,             // Information about threads and task execution

        // Network-related diagnostics
        RequestHeaders,          // HTTP request headers
        ResponseHeaders,         // HTTP response headers
        NetworkTraffic,          // Network trace (Wireshark, Fiddler, etc.)
        DNSLookup,               // DNS resolution results
        NetworkLatency,          // Network latency information

        // IIS/Hosting environment diagnostics
        IISRequestTrace,         // IIS Failed Request Tracing (FREB) logs
        WorkerProcessMemory,     // Memory usage of the worker process
        AppPoolRecycles,         // Information about application pool recycles
        HostingStartupLogs,      // Logs generated during application startup

        // Database-related diagnostics
        DatabaseLogs,            // Logs from the database (e.g., SQL Server logs, slow query logs)
        QueryExecutionPlan,      // SQL query execution plan to diagnose performance issues
        DatabaseConnections,     // Number of active/open database connections

        // Client-side diagnostics (for Blazor and web-based issues)
        BrowserConsoleLogs,      // Browser console logs (useful for Blazor WASM)
        NetworkInspectorLogs,    // Network requests logged by the browser's network tab
        UIErrors,                // UI errors such as Blazor rendering or JavaScript interop issues

        // Deployment-related diagnostics
        DockerLogs,              // Logs from Docker containers if the app is containerized
        KubernetesLogs,          // Logs from Kubernetes cluster if deployed there
        CI_CDLogs,               // Continuous Integration/Deployment logs (e.g., GitHub Actions, Azure Pipelines)

        // Miscellaneous
        CustomMetrics,           // Any custom application metrics (e.g., Prometheus metrics)
        UserSessionData,         // User-specific session data for reproducing issues
        ThreadDumps,             // Thread dumps to analyze thread activity
        MemoryDumps,             // Memory dump of the process for debugging
        ConfigurationDiff,       // Diff between local and production configurations
        HealthChecks,            // Results of health checks if implemented
        SecuritySettings,        // Security-related settings such as HTTPS, CSP, etc.
        FirewallLogs             // Logs related to firewall or reverse proxy configurations
    }
}
